PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

INSERT {
  GRAPH ?g {
   ?s ?p ?o .
  }
}
WHERE {
  VALUES ?h {
    <http://mu.semte.ch/graphs/temp/AdditionalAction>
    <http://mu.semte.ch/graphs/temp/ApplicationFlow>
    <http://mu.semte.ch/graphs/temp/ApplicationForm>
    <http://mu.semte.ch/graphs/temp/ApplicationFormEntry>
    <http://mu.semte.ch/graphs/temp/ApplicationFormTable>
    <http://mu.semte.ch/graphs/temp/ApplicationStep>
    <http://mu.semte.ch/graphs/temp/BankAccount>
    <http://mu.semte.ch/graphs/temp/BesluitBestuurseenheid>
    <http://mu.semte.ch/graphs/temp/BestuurseenheidClassificatieCode>
    <http://mu.semte.ch/graphs/temp/Bestuursorgaan>
    <http://mu.semte.ch/graphs/temp/BestuursorgaanClassificatieCode>
    <http://mu.semte.ch/graphs/temp/BicycleInfrastructureAccountabilityUploadFormData>
    <http://mu.semte.ch/graphs/temp/BicycleInfrastructureAwardUploadFormData>
    <http://mu.semte.ch/graphs/temp/BicycleInfrastructureDecisionUploadFormData>
    <http://mu.semte.ch/graphs/temp/BicycleInfrastructureEstimatedCostEntry>
    <http://mu.semte.ch/graphs/temp/BicycleInfrastructureEstimatedCostTable>
    <http://mu.semte.ch/graphs/temp/BicycleInfrastructureInvoiceUploadFormData>
    <http://mu.semte.ch/graphs/temp/BicycleInfrastructureJustificationCostsUploadFormData>
    <http://mu.semte.ch/graphs/temp/BicycleInfrastructureJustificationExpropriationsUploadFormData>
    <http://mu.semte.ch/graphs/temp/BicycleInfrastructureObjectiveEntry>
    <http://mu.semte.ch/graphs/temp/BicycleInfrastructureObjectiveTable>
    <http://mu.semte.ch/graphs/temp/BicycleInfrastructurePicturesUploadFormData>
    <http://mu.semte.ch/graphs/temp/BicycleInfrastructureReportUploadFormData>
    <http://mu.semte.ch/graphs/temp/ClimateAttachmentFormData>
    <http://mu.semte.ch/graphs/temp/ClimateEntry>
    <http://mu.semte.ch/graphs/temp/ClimateSignedPactFormData>
    <http://mu.semte.ch/graphs/temp/ClimateTable>
    <http://mu.semte.ch/graphs/temp/Concept>
    <http://mu.semte.ch/graphs/temp/ContactPoint>
    <http://mu.semte.ch/graphs/temp/ContactTracingObjectiveFourFormData>
    <http://mu.semte.ch/graphs/temp/ContactTracingObjectiveOneFormData>
    <http://mu.semte.ch/graphs/temp/ContactTracingObjectiveThreeFormData>
    <http://mu.semte.ch/graphs/temp/ContactTracingObjectiveTwoFormData>
    <http://mu.semte.ch/graphs/temp/Criterion>
    <http://mu.semte.ch/graphs/temp/CriterionRequirement>
    <http://mu.semte.ch/graphs/temp/EngagementEntry>
    <http://mu.semte.ch/graphs/temp/EngagementTable>
    <http://mu.semte.ch/graphs/temp/FileDataObject>
    <http://mu.semte.ch/graphs/temp/FinancingPartner>
    <http://mu.semte.ch/graphs/temp/MonetaryAmount>
    <http://mu.semte.ch/graphs/temp/NooddorpenAccountabilityProofFormData>
    <http://mu.semte.ch/graphs/temp/NooddorpenAccountabilitySummaryFormData>
    <http://mu.semte.ch/graphs/temp/Participation>
    <http://mu.semte.ch/graphs/temp/Period>
    <http://mu.semte.ch/graphs/temp/PeriodOfTime>
    <http://mu.semte.ch/graphs/temp/PlanLivingTogetherEntry>
    <http://mu.semte.ch/graphs/temp/PlanLivingTogetherSubsidyWithdrawalRule>
    <http://mu.semte.ch/graphs/temp/PlanLivingTogetherTable>
    <http://mu.semte.ch/graphs/temp/PoliticalReferenceContactPoint>
    <http://mu.semte.ch/graphs/temp/ProjectOnderdeelPrivatePartnerUnit>
    <http://mu.semte.ch/graphs/temp/ProjectOnderdeelPubliekePartnerUnit>
    <http://mu.semte.ch/graphs/temp/ProjectOnderdeelStadUnit>
    <http://mu.semte.ch/graphs/temp/ProjectOnderdeelTimingUnit>
    <http://mu.semte.ch/graphs/temp/ProjectOnderdeelUnit>
    <http://mu.semte.ch/graphs/temp/RemoteDataObject>
    <http://mu.semte.ch/graphs/temp/RequirementGroup>
    <http://mu.semte.ch/graphs/temp/SubmissionDocument>
    <http://mu.semte.ch/graphs/temp/SubmissionDocumentStatus>
    <http://mu.semte.ch/graphs/temp/SubsidieAanvraag>
    <http://mu.semte.ch/graphs/temp/SubsidieBedragListingUnit>
    <http://mu.semte.ch/graphs/temp/SubsidiemaatregelAanbod>
    <http://mu.semte.ch/graphs/temp/SubsidiemaatregelAanbodReeks>
    <http://mu.semte.ch/graphs/temp/SubsidiemaatregelConsumptie>
    <http://mu.semte.ch/graphs/temp/SubsidiemaatregelConsumptieStatus>
    <http://mu.semte.ch/graphs/temp/Subsidieprocedurestap>
    <http://mu.semte.ch/graphs/temp/UrbanRenewalApplicationFormFormData>
    <http://mu.semte.ch/graphs/temp/UrbanRenewalAttachmentsFormData>
    <http://mu.semte.ch/graphs/temp/Werkingsgebied>
  }

  GRAPH ?h {
    ?s a ?type ;
       ?p ?o ;
       ext:wasInGraph ?g .
  }
}
