SELECT COUNT DISTINCT * WHERE {
  VALUES ?type {
    <http://data.vlaanderen.be/ns/subsidie#SubsidiemaatregelAanbod>
  }

  GRAPH ?g {
    ?s a ?type ;
      ?p ?o .
  }

  FILTER(regex(STR(?g), "(http://mu.semte.ch/graphs/organizations/.*/LoketLB-subsidies|http://mu.semte.ch/graphs/public)"))
}
