SELECT COUNT DISTINCT * WHERE {
  VALUES ?type {
    <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure/invoice-upload/FormData>
  }

  GRAPH ?g {
    ?s a ?type ;
      ?p ?o .
  }

  FILTER(regex(STR(?g), "(http://mu.semte.ch/graphs/organizations/.*/LoketLB-subsidies)"))
}
