DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?type {
    <http://lblod.data.gift/vocabularies/subsidie/urban-renewal/urban-renewal-application-form/FormData>
  }

  GRAPH ?g {
    ?s a ?type ;
      ?p ?o .
  }
}
