DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?type {
    <http://lblod.data.gift/vocabularies/subsidie/projectOnderdeelTimingUnit>
  }

  GRAPH ?g {
    ?s a ?type ;
      ?p ?o .
  }
}
