DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?type {
    <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject>
  }

  GRAPH ?g {
    ?s a ?type ;
      ?p ?o .
  }
}
